<a href="https://colab.research.google.com/github/aeshhaa/Credit-Card-Fraud-Detection/blob/main/Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [2]:
# loading the dataset to a Pandas Dataframe
credit_card_data = pd.read_csv('/content/Fraud Detection.csv')

In [3]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7968,10980,1.284388,-0.013181,0.646174,0.198985,-0.568675,-0.526121,-0.448235,-0.167709,1.773223,...,-0.101868,-0.030298,-0.081412,-0.123281,0.278808,1.064001,-0.090181,0.000481,15.95,0.0
7969,10981,1.190428,-0.122329,0.954945,0.267101,-0.971026,-0.652279,-0.612992,-0.003909,1.633117,...,-0.015001,0.127027,0.012079,0.534409,0.112179,1.004483,-0.100188,-0.004774,14.95,0.0
7970,10981,-0.725175,0.298202,1.824761,-2.587170,0.283605,-0.016617,0.153659,0.045084,-0.197611,...,-0.017097,-0.070535,-0.442861,-0.895837,0.624743,-0.510601,-0.031142,0.025564,12.95,0.0
7971,10981,1.226153,-0.129645,0.735197,0.142752,-0.703245,-0.349641,-0.612641,0.020507,1.648986,...,-0.047936,0.040196,-0.057391,-0.012386,0.187685,1.037786,-0.100081,-0.009869,15.95,0.0
7972,10981,1.145381,-0.059349,0.968088,0.267891,-0.822582,-0.597727,-0.450197,-0.119747,1.338188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7973 entries, 0 to 7972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    7973 non-null   int64
 1   V1      7973 non-null   float64
 2   V2      7973 non-null   float64
 3   V3      7973 non-null   float64
 4   V4      7973 non-null   float64
 5   V5      7973 non-null   float64
 6   V6      7973 non-null   float64
 7   V7      7973 non-null   float64
 8   V8      7973 non-null   float64
 9   V9      7973 non-null   float64
 10  V10     7973 non-null   float64
 11  V11     7973 non-null   float64
 12  V12     7973 non-null   float64
 13  V13     7973 non-null   float64
 14  V14     7973 non-null   float64
 15  V15     7972 non-null   float64
 16  V16     7972 non-null   float64
 17  V17     7972 non-null   float64
 18  V18     7972 non-null   float64
 19  V19     7972 non-null   float64
 20  V20     7972 non-null   float64
 21  V21     7972 non-null   float64
 22  V22     7972 non-null   float64
 23  V23     7972 non-null   float64
 24  V24     7972 non-null   float64
 25  V25     7972 non-null   float64
 26  V26     7972 non-null   float64
 27  V27     7972 non-null   float64
 28  V28     7972 non-null   float64
 29  Amount  7972 non-null   float64
 30  Class   7972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.9 MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
# distribution of legit transaction & fraudulent transaction
credit_card_data['Class'].value_counts()

Class
0.0    7947
1.0      25
Name: count, dtype: int64

This dataset is highly unbalanced
0 ---> Normal transaction
1 ---> Fraudulent Transaction

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class==0]
fraud = credit_card_data[credit_card_data.Class==1]

In [9]:
print(legit.shape)
print(fraud.shape)

(7947, 31)
(25, 31)

In [10]:
# statistical measures of the data
legit.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [12]:
#compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,0.042418,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent transactions

In [13]:
legit_sample = legit.sample(n=492)

Number of Fraudulent transactions--> 492

Concatenating two DataFrames

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [15]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1928,1488,1.095605,0.480269,0.695005,2.327792,0.027834,0.249908,-0.057874,0.172924,-0.976953,...,0.007788,-0.035808,0.037008,-0.011638,0.314311,-0.061434,0.002632,0.011371,7.58,0.0
6812,8592,-23.066842,-25.640527,-3.080313,4.866932,6.901397,-4.074335,2.027345,-2.688652,3.402966,...,-5.378106,3.312971,13.876221,-0.572177,5.525093,0.906980,3.358822,3.553906,845.73,0.0
2445,2012,-0.410280,1.037655,1.316502,-0.043593,0.123976,-0.688113,0.571562,0.081511,-0.641320,...,-0.210402,-0.584620,-0.022303,0.276405,-0.191296,0.054836,0.240444,0.088677,1.78,0.0
7753,10795,0.934622,-0.508516,0.622316,0.373675,-0.657333,0.005687,-0.294369,0.015552,1.742239,...,-0.098565,-0.049703,-0.112420,0.276209,0.253568,1.059601,-0.101683,0.003071,124.80,0.0
4580,3922,0.929863,-0.333008,0.658420,1.206740,-0.514777,0.352452,-0.528177,0.253843,1.713555,...,0.079558,0.163367,-0.164018,-0.412602,0.329783,-0.306618,-0.007327,0.022407,117.11,0.0

In [16]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6870,8757,-1.863756,3.442644,-4.468260,2.805336,-2.118412,-2.332285,-4.261237,1.701682,-1.439396,...,0.667927,-0.516242,-0.012218,0.070614,0.058504,0.304883,0.418012,0.208858,1.00,1.0
6882,8808,-4.617217,1.695694,-3.114372,4.328199,-1.873257,-0.989908,-4.577265,0.472216,0.472017,...,0.481830,0.146023,0.117039,-0.217565,-0.138776,-0.424453,-1.002041,0.890780,1.10,1.0
6899,8878,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1.0
6903,8886,-2.535852,5.793644,-7.618463,6.395830,-0.065210,-3.136372,-3.104557,1.823233,-3.878658,...,0.716720,-0.448060,-0.402407,-0.288835,1.011752,0.425965,0.413140,0.308205,1.00,1.0
6971,9064,-3.499108,0.258555,-4.489558,4.853894,-6.974522,3.628382,5.431271,-1.946734,-0.775680,...,-1.052368,0.204817,-2.119007,0.170279,-0.393844,0.296367,1.985913,-0.900452,1809.68,1.0

In [17]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     25
Name: count, dtype: int64

In [18]:
new_dataset.groupby('Class').mean

Splitting the data into features and targets

In [20]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

       Time         V1         V2        V3        V4        V5        V6  \
1928   1488   1.095605   0.480269  0.695005  2.327792  0.027834  0.249908
6812   8592 -23.066842 -25.640527 -3.080313  4.866932  6.901397 -4.074335
2445   2012  -0.410280   1.037655  1.316502 -0.043593  0.123976 -0.688113
7753  10795   0.934622  -0.508516  0.622316  0.373675 -0.657333  0.005687
4580   3922   0.929863  -0.333008  0.658420  1.206740 -0.514777  0.352452
...     ...        ...        ...       ...       ...       ...       ...
6870   8757  -1.863756   3.442644 -4.468260  2.805336 -2.118412 -2.332285
6882   8808  -4.617217   1.695694 -3.114372  4.328199 -1.873257 -0.989908
6899   8878  -2.661802   5.856393 -7.653616  6.379742 -0.060712 -3.131550
6903   8886  -2.535852   5.793644 -7.618463  6.395830 -0.065210 -3.136372
6971   9064  -3.499108   0.258555 -4.489558  4.853894 -6.974522  3.628382

            V7        V8        V9  ...        V20       V21       V22  \
1928 -0.057874  0.172924 -0.976953  ...  -0.170242  0.007788 -0.035808
6812  2.027345 -2.688652  3.402966  ... -13.276034 -5.378106  3.312971
2445  0.571562  0.081511 -0.641320  ...   0.128563 -0.210402 -0.584620
7753 -0.294369  0.015552  1.742239  ...   0.096187 -0.098565 -0.049703
4580 -0.528177  0.253843  1.713555  ...  -0.104748  0.079558  0.163367
...        ...       ...       ...  ...        ...       ...       ...
6870 -4.261237  1.701682 -1.439396  ...   0.360924  0.667927 -0.516242
6882 -4.577265  0.472216  0.472017  ...  -0.039046  0.481830  0.146023
6899 -3.103570  1.778492 -3.831154  ...   0.399097  0.734775 -0.435901
6903 -3.104557  1.823233 -3.878658  ...   0.408704  0.716720 -0.448060
6971  5.431271 -1.946734 -0.775680  ...  -3.042626 -1.052368  0.204817

            V23       V24       V25       V26       V27       V28   Amount
1928   0.037008 -0.011638  0.314311 -0.061434  0.002632  0.011371     7.58
6812  13.876221 -0.572177  5.525093  0.906980  3.358822  3.553906   845.73
2445  -0.022303  0.276405 -0.191296  0.054836  0.240444  0.088677     1.78
7753  -0.112420  0.276209  0.253568  1.059601 -0.101683  0.003071   124.80
4580  -0.164018 -0.412602  0.329783 -0.306618 -0.007327  0.022407   117.11
...         ...       ...       ...       ...       ...       ...      ...
6870  -0.012218  0.070614  0.058504  0.304883  0.418012  0.208858     1.00
6882   0.117039 -0.217565 -0.138776 -0.424453 -1.002041  0.890780     1.10
6899  -0.384766 -0.286016  1.007934  0.413196  0.280284  0.303937     1.00
6903  -0.402407 -0.288835  1.011752  0.425965  0.413140  0.308205     1.00
6971  -2.119007  0.170279 -0.393844  0.296367  1.985913 -0.900452  1809.68

[517 rows x 30 columns]

In [22]:
print(Y)

1928    0.0
6812    0.0
2445    0.0
7753    0.0
4580    0.0
       ...
6870    1.0
6882    1.0
6899    1.0
6903    1.0
6971    1.0
Name: Class, Length: 517, dtype: float64

Split the data into Training data and testing data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(517, 30) (413, 30) (104, 30)

Model Training

Logistic Regression

In [31]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [32]:
model = LogisticRegression()

In [33]:
# training the Logistic Regression Model with Training Data
model.fit(X_train_scaled, Y_train)

LogisticRegression()

Model Evaluation

Accuracy Score

In [45]:
# accuracy on training data
X_train_prediction = model.predict(X_train_scaled)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [43]:
print('Accuracy on Training data: ', training_data_accuracy)

Accuracy on Training data:  1.0

In [41]:
# accuracy on test data
X_test_prediction = model.predict(X_test_scaled)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [46]:
print('Accuracy score on Test data: ', test_data_accuracy)

Accuracy score on Test data:  0.9807692307692307